#数据库配置
spring:
  datasource:
    url: jdbc:mysql://192.168.113.138:8066/yangSchema #这个地址是myCat地址,也可以配置为数据库实际地址
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#日志打印
logging:
  level:
    com.yang.code.dao.*: TRACE
#mybatis mapper扫描位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
#端口号
server:
  port: 9999
